In [ ]:
import numpy as np

x = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
print(x)
print(y)
x = x / np.amax(x, axis=0)
y = y / 100

[[2. 9.]
 [1. 5.]
 [3. 6.]]
[[92.]
 [86.]
 [89.]]


In [4]:
print(x)
print(y)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def derivatives_sigmoid(x):
    return x * (1 - x)


epoch = 5000
lr = 0.1
inputlayer_neurons = 2
hiddenlayer_neurons = 3
output_neurons = 1

In [ ]:
wh = np.random.uniform(size=(inputlayer_neurons, hiddenlayer_neurons))
bh = np.random.uniform(size=(1, hiddenlayer_neurons))
wout = np.random.uniform(size=(hiddenlayer_neurons, output_neurons))
bout = np.random.uniform(size=(1, output_neurons))

In [8]:
print(wh)
print(bh)
print(wout)
print(bout)

[[0.1961993  0.27094342 0.29102008]
 [0.80566433 0.26823431 0.02057251]]
[[0.77813309 0.23467704 0.81122203]]
[[0.54091735]
 [0.44503714]
 [0.08714422]]
[[0.19475703]]


In [32]:
# for i in range(epoch):
#     hinop = sigmoid(np.dot(x, wh) + bh)
#     op = sigmoid(np.dot(hinop, wout) + bout)

#     dop = derivatives_sigmoid(op) * (y - op)
#     dhn = derivatives_sigmoid(hinop) * np.dot(wout, dop.T)

#     wout += lr * np.dot(hinop.T, dop)
#     wh += lr * np.dot(x.T, dhn)
for _ in range(epoch):
    # Forward Propagation
    hidden = sigmoid(np.dot(x, wh))
    output = sigmoid(np.dot(hidden, wout))

    # Backpropagation
    output_error = y - output
    output_delta = output_error * derivatives_sigmoid(output)

    hidden_error = np.dot(wout.T, output_delta)
    hidden_delta = hidden_error * derivatives_sigmoid(hidden)

    # Update weights
    wout += np.dot(hidden.T, output_delta) * lr
    wh += np.dot(x.T, hidden_delta) * lr

# Print results
print("Input: \n", x)
print("Actual output: \n", y)
print("Predicted output: \n", output)

Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output: 
 [[0.92]
 [0.86]
 [0.89]]
Predicted output: 
 [[0.90129896]
 [0.872398  ]
 [0.89654132]]


In [33]:
# for i in range(epoch):
#     hinop = sigmoid(np.dot(x, wh) + bh)
#     op = sigmoid(np.dot(hinop, wout) + bout)

#     dop = derivatives_sigmoid(op) * (y - op)
#     dhn = derivatives_sigmoid(hinop) * np.dot(wout, dop.T)

#     wout += lr * np.dot(hinop.T, dop)
#     wh += lr * np.dot(x.T, dhn)
for _ in range(epoch):
    # Forward Propagation
    hidden = sigmoid(np.dot(x, wh))
    output = sigmoid(np.dot(hidden, wout))

    # Backpropagation
    output_error = y - output
    output_delta = output_error * derivatives_sigmoid(output)

    hidden_error = np.dot(output_delta, wout.T)
    hidden_delta = hidden_error * derivatives_sigmoid(hidden)

    # Update weights
    wout += np.dot(hidden.T, output_delta) * lr
    wh += np.dot(x.T, hidden_delta) * lr

# Print results
print("Input: \n", x)
print("Actual output: \n", y)
print("Predicted output: \n", output)

Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output: 
 [[0.92]
 [0.86]
 [0.89]]
Predicted output: 
 [[0.90129925]
 [0.87174721]
 [0.8958699 ]]


In [ ]:
# for i in range(epoch):
#     hinp1 = np.dot(x, wh)
#     hinp = hinp1 + bh
#     hlayer_act = sigmoid(hinp)
#     outinp1 = np.dot(hlayer_act, wout)
#     outinp = outinp1 + bout
#     output = sigmoid(outinp)

#     ED = y - output
#     outgrad = derivatives_sigmoid(output)
#     d_output = ED * outgrad
#     EH = d_output.dot(wout.T)
#     hiddengrad = derivatives_sigmoid(hlayer_act)
#     d_hidden = EH * hiddengrad
#     wout += hlayer_act.T.dot(d_output) * lr
#     wh += x.T.dot(d_hidden) * lr