In [1]:
import numpy as np

In [2]:
A = np.random.rand(5, 8)
U, S, VT = np.linalg.svd(A)

In [4]:
print(U)
print(S)
print(VT)

[[ 0.32711135  0.45364851 -0.57905629 -0.54305645  0.2387147 ]
 [ 0.56843227 -0.75983438 -0.06792414 -0.27815281 -0.13249076]
 [ 0.48305329  0.10768218  0.42096902  0.24792471  0.71859758]
 [ 0.47364913  0.44966948  0.4352006  -0.07359709 -0.61533549]
 [ 0.3349611   0.05528706 -0.54172469  0.74889086 -0.17447419]]
[3.50537709 0.92392747 0.85713046 0.64701848 0.35681796]
[[ 0.21771936  0.36968134  0.39235098  0.30946442  0.28138342  0.38194879
   0.2822464   0.5113726 ]
 [ 0.13248985 -0.40153725 -0.34018482  0.13247824 -0.3707999  -0.09886556
   0.65715645  0.32987347]
 [-0.35686846  0.41956819  0.05864934 -0.51786888 -0.04483785  0.10774192
   0.58545744 -0.26191667]
 [-0.0563597  -0.14102977  0.47213794 -0.22885311  0.23585412 -0.74802821
   0.09691283  0.27763419]
 [ 0.36365234  0.65797097 -0.42373392 -0.09618537 -0.18025496 -0.38424253
  -0.13906656  0.2157671 ]
 [ 0.28968561 -0.26281961 -0.24150981 -0.68207678  0.36554549  0.29697196
  -0.10642495  0.30051665]
 [-0.13199928  0.0231