In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error, accuracy_score

In [ ]:
# load the iris dataset
# X contains the features and y contains the labels
iris = datasets.load_iris()
x = iris.data
y = iris.target
# split data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42
)

In [ ]:
# summerise the features by removing the mean and scaling to unit variance
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
# create a logistic regression model model LogisticRegression()
# train the model
model = LogisticRegression()
model.fit(x_train, y_train)
print(x_train)
print(y_train)

[[-0.4134164  -1.46200287 -0.09951105 -0.32339776]
 [ 0.55122187 -0.50256349  0.71770262  0.35303182]
 [ 0.67180165  0.21701605  0.95119225  0.75888956]
 [ 0.91296121 -0.02284379  0.30909579  0.2177459 ]
 [ 1.63643991  1.41631528  1.30142668  1.70589097]
 [-0.17225683 -0.26270364  0.19235097  0.08245999]
 [ 2.11875905 -0.02284379  1.59328871  1.16474731]
 [-0.29283662 -0.02284379  0.36746819  0.35303182]
 [-0.89573553  1.17645543 -1.44207638 -1.40568508]
 [ 2.23933883 -0.50256349  1.65166111  1.0294614 ]
 [-0.05167705 -0.74242333  0.13397857 -0.32339776]
 [-0.77515575  0.93659559 -1.44207638 -1.40568508]
 [-1.01631531  1.17645543 -1.50044878 -1.27039917]
 [-0.89573553  1.89603497 -1.15021435 -1.13511325]
 [-1.01631531 -2.42144225 -0.21625586 -0.32339776]
 [ 0.55122187 -0.74242333  0.60095781  0.75888956]
 [-1.25747488  0.93659559 -1.15021435 -1.40568508]
 [-1.01631531 -0.02284379 -1.32533157 -1.40568508]
 [-0.89573553  0.69673574 -1.26695916 -0.99982734]
 [-0.29283662 -0.74242333  0.19

In [6]:
y_pred = model.predict(x_test)
print(y_pred)
print(y_test)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]


In [7]:
print(f"Accuracy Score: {accuracy_score(y_test, y_pred)}")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred)}")

Accuracy Score: 1.0
Mean Squared Error: 0.0
