In [11]:
import numpy as np

# perform SVD on a random matrix

In [12]:
A = np.random.rand(5, 8)
print(A)

[[0.10017286 0.1098538  0.32352426 0.13180383 0.02627802 0.19456916
  0.2735599  0.53676867]
 [0.32427029 0.63448396 0.82386424 0.61622816 0.85743044 0.39334262
  0.85398851 0.95957459]
 [0.04788942 0.56859225 0.10941614 0.7298214  0.62523562 0.08738594
  0.61578102 0.32814691]
 [0.45615923 0.18608208 0.53394955 0.17301865 0.8411926  0.16099003
  0.19180359 0.94939002]
 [0.80473969 0.47017991 0.96536097 0.99162673 0.52563925 0.58462516
  0.52349539 0.87835901]]


In [21]:
U, S, VT = np.linalg.svd(A)
print("U:", U, "S:", S, "VT:", VT, sep="\n")

U:
[[ 0.18798919  0.20053412 -0.05374378 -0.68810878  0.66937587]
 [ 0.58664346 -0.16023185  0.24597575 -0.47568468 -0.58599934]
 [ 0.32898259 -0.79662273  0.15901986  0.2472564   0.41320655]
 [ 0.39496229  0.51133573  0.62209012  0.39726802  0.19422299]
 [ 0.59689594  0.195038   -0.72410228  0.28508383  0.0088604 ]]
S:
[3.41044308 0.85746408 0.70515425 0.42797668 0.19405284]
VT:
[[ 0.25959348  0.27388465  0.40089794  0.3772578   0.39866634  0.20778022
   0.33521209  0.48998081]
 [ 0.37340944 -0.40320667  0.35804945 -0.43363333 -0.11375807  0.11979767
  -0.43424057  0.40730239]
 [-0.30765945  0.02252365 -0.23284663 -0.49614158  0.64042828 -0.3162232
   0.04755647  0.30340932]
 [ 0.46567134 -0.06741593 -0.23397479  0.34595078  0.49693132 -0.16066694
  -0.50651104 -0.27362587]
 [-0.03841086 -0.11862883 -0.56043677  0.36626309 -0.30134082 -0.14275593
  -0.10814846  0.64290913]
 [-0.34055686 -0.19934278 -0.21417187  0.05588764  0.23997699  0.84040269
  -0.17715574 -0.00637733]
 [-0.3675451

In [28]:
k = 3
u_k = U[:, :k]
s_k = np.diag(S[:k])
vt_k = VT[:k, :]

In [29]:
print("u_k", u_k, "s_k", s_k, "vt_k", vt_k, sep="\n\n")

u_k

[[ 0.18798919  0.20053412 -0.05374378]
 [ 0.58664346 -0.16023185  0.24597575]
 [ 0.32898259 -0.79662273  0.15901986]
 [ 0.39496229  0.51133573  0.62209012]
 [ 0.59689594  0.195038   -0.72410228]]

s_k

[[3.41044308 0.         0.        ]
 [0.         0.85746408 0.        ]
 [0.         0.         0.70515425]]

vt_k

[[ 0.25959348  0.27388465  0.40089794  0.3772578   0.39866634  0.20778022
   0.33521209  0.48998081]
 [ 0.37340944 -0.40320667  0.35804945 -0.43363333 -0.11375807  0.11979767
  -0.43424057  0.40730239]
 [-0.30765945  0.02252365 -0.23284663 -0.49614158  0.64042828 -0.3162232
   0.04755647  0.30340932]]


In [31]:
a_reduced = np.dot(u_k, np.dot(s_k, vt_k))
print(a_reduced)
print(u_k @ s_k @ vt_k)

[[0.24229987 0.10540939 0.3274175  0.18610895 0.21176401 0.16579681
  0.13844304 0.37267713]
 [0.41470469 0.60726944 0.71250122 0.72830704 0.92432977 0.34440026
  0.73857392 0.9769776 ]
 [0.00169203 0.58523832 0.17911336 0.66384449 0.59681304 0.11583444
  0.67805177 0.30555102]
 [0.3784328  0.2020153  0.59485288 0.10039531 0.76806101 0.19368726
  0.2819974  0.97168135]
 [0.74798953 0.47860925 0.99487166 0.9487878  0.46552717 0.60447346
  0.58548036 0.91063848]]
[[0.24229987 0.10540939 0.3274175  0.18610895 0.21176401 0.16579681
  0.13844304 0.37267713]
 [0.41470469 0.60726944 0.71250122 0.72830704 0.92432977 0.34440026
  0.73857392 0.9769776 ]
 [0.00169203 0.58523832 0.17911336 0.66384449 0.59681304 0.11583444
  0.67805177 0.30555102]
 [0.3784328  0.2020153  0.59485288 0.10039531 0.76806101 0.19368726
  0.2819974  0.97168135]
 [0.74798953 0.47860925 0.99487166 0.9487878  0.46552717 0.60447346
  0.58548036 0.91063848]]


In [10]:
import numpy as np

# Example matrix
A = np.array([[1, 2], [3, 4], [5, 6]])

# Perform SVD
U, S, Vt = np.linalg.svd(A, full_matrices=False)

# Reduced rank approximation (keeping only the first singular value)
k = 1  # Rank of the reduced approximation
Ur = U[:, :k]
Sr = np.diag(S[:k])
Vtr = Vt[:k, :]

# Reconstruct the reduced matrix
A_reduced = Ur @ Sr @ Vtr

print("Original matrix:")
print(A)
print("\nReduced matrix:")
print(A_reduced)

Original matrix:
[[1 2]
 [3 4]
 [5 6]]

Reduced matrix:
[[1.35662819 1.71846235]
 [3.09719707 3.92326845]
 [4.83776596 6.12807454]]


In [32]:
2 @ 3

TypeError: unsupported operand type(s) for @: 'int' and 'int'